GROUP_REPOS = [
    [
        "group a",
        "ZeroDownTime",
        ["https://github.com/ZeroDownTime-ITU/minitwit_project"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "catch(RuntimeException){goto f;}",
        ["https://github.com/JohannesHackl/DevOps26_RE_minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group c",
        "group c",
        ["https://github.com/jskoven/Devops2026_jklo_jakst_aing_asjo_mbln"],
        "http://161.35.68.148:5001/",
        "http://161.35.68.148:5001/",
    ],
    [
        "group d",
        "Dense Dino Nuggets",
        ["https://github.com/Slug-Boi-ITU-Repositories/Dense-Dino-Nuggets"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "Jams",
        ["https://github.com/sebsthiel/minitwit-devops"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "if time > 16 {beer++;}",
        ["https://github.com/TienCamLy/MiniTwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "DevOpps",
        ["https://git.marfavi.com/DevOpps/itu-minitwit-migration"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "I Terroni",
        ["https://github.com/stegish/I-Terroni-DevOps"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "Pat Myaz",
        ["https://github.com/ITU-DevOps2026/ITU-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group m",
        "Holy C Enjoyers",
        ["https://github.com/MudiLoodi/minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "Diversity",
        ["https://github.com/huncut47/diversity"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group o",
        "Rollback & Relax",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group a",
        "EastTops",
        ["https://github.com/AntohaY/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "DevTroopers",
        ["https://github.com/DevTroopers-ITU/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
